// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAPApplicationOperatorConfig) DeepCopyInto(out *EAPApplicationOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAPApplicationOperatorConfig.
func (in *EAPApplicationOperatorConfig) DeepCopy() *EAPApplicationOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(EAPApplicationOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EAPApplicationOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAPApplicationOperatorConfigList) DeepCopyInto(out *EAPApplicationOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EAPApplicationOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAPApplicationOperatorConfigList.
func (in *EAPApplicationOperatorConfigList) DeepCopy() *EAPApplicationOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(EAPApplicationOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EAPApplicationOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAPApplicationOperatorConfigSpec) DeepCopyInto(out *EAPApplicationOperatorConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAPApplicationOperatorConfigSpec.
func (in *EAPApplicationOperatorConfigSpec) DeepCopy() *EAPApplicationOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(EAPApplicationOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAPApplicationOperatorConfigStatus) DeepCopyInto(out *EAPApplicationOperatorConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAPApplicationOperatorConfigStatus.
func (in *EAPApplicationOperatorConfigStatus) DeepCopy() *EAPApplicationOperatorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(EAPApplicationOperatorConfigStatus)
	in.DeepCopyInto(out)
	return out
}
